"""add phase 3 core schema and identity

Revision ID: 20260721_0002
Revises: 20260721_0001
Create Date: 2026-07-21 20:12:36.976215
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '20260721_0002'
down_revision: str | None = '20260721_0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluation_runs',
    sa.Column('dataset_version', sa.String(length=100), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('aggregate_metrics', sa.JSON(), nullable=True),
    sa.Column('report_uri', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permissions',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='RESTRICT'),
    sa.CheckConstraint("status IN ('active','inactive')", name='ck_users_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_users_active_email', 'users', ['email'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_table('audit_logs',
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=True),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('source_ip_hash', sa.String(length=128), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_actor', 'audit_logs', ['actor_id'], unique=False)
    op.create_index('ix_audit_logs_occurred', 'audit_logs', ['occurred_at'], unique=False)
    op.create_index('ix_audit_logs_request', 'audit_logs', ['request_id'], unique=False)
    op.create_index('ix_audit_logs_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_table('conversations',
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='RESTRICT'),
    sa.CheckConstraint("status IN ('active','archived')", name='ck_conversations_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversations_owner_updated', 'conversations', ['owner_id', 'updated_at'], unique=False)
    op.create_table('documents',
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('media_type', sa.String(length=255), nullable=False),
    sa.Column('byte_size', sa.BigInteger(), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('failure_code', sa.String(length=100), nullable=True),
    sa.Column('classification', sa.String(length=50), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("status IN ('uploaded','processing','ready','failed')", name='ck_documents_status'),
    sa.CheckConstraint('byte_size >= 0', name='ck_documents_byte_size_nonnegative'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index('ix_documents_owner_status_updated', 'documents', ['owner_id', 'status', 'updated_at'], unique=False)
    op.create_table('refresh_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_id', sa.Uuid(), nullable=True),
    sa.Column('reuse_detected', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['replaced_by_id'], ['refresh_sessions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_refresh_sessions_expiry', 'refresh_sessions', ['expires_at'], unique=False)
    op.create_index('ix_refresh_sessions_family', 'refresh_sessions', ['family_id'], unique=False)
    op.create_index('ix_refresh_sessions_user', 'refresh_sessions', ['user_id'], unique=False)
    op.create_table('roles',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('document_chunks',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('section', sa.String(length=255), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('embedding_model', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('ordinal >= 0', name='ck_document_chunks_ordinal_nonnegative'),
    sa.CheckConstraint('token_count IS NULL OR token_count >= 0', name='ck_chunks_tokens_nonnegative'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'ordinal', name='uq_document_chunks_document_ordinal')
    )
    op.create_index('ix_document_chunks_document', 'document_chunks', ['document_id'], unique=False)
    op.create_table('messages',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('author_user_id', sa.Uuid(), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('safety_decision', sa.String(length=32), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("role IN ('user','assistant','system','tool')", name='ck_messages_role'),
    sa.CheckConstraint("status IN ('pending','completed','failed')", name='ck_messages_status'),
    sa.CheckConstraint('sequence >= 0', name='ck_messages_sequence_nonnegative'),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'sequence', name='uq_messages_conversation_sequence')
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permissions_role_permission')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_by', sa.Uuid(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_roles_user_role')
    )
    op.create_table('agent_executions',
    sa.Column('conversation_id', sa.Uuid(), nullable=True),
    sa.Column('message_id', sa.Uuid(), nullable=True),
    sa.Column('parent_execution_id', sa.Uuid(), nullable=True),
    sa.Column('agent_type', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('input_token_count', sa.Integer(), nullable=True),
    sa.Column('output_token_count', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('input_token_count IS NULL OR input_token_count >= 0', name='ck_agent_input_tokens'),
    sa.CheckConstraint('output_token_count IS NULL OR output_token_count >= 0', name='ck_agent_output_tokens'),
    sa.CheckConstraint('estimated_cost IS NULL OR estimated_cost >= 0', name='ck_agent_cost_nonnegative'),
    sa.CheckConstraint('latency_ms IS NULL OR latency_ms >= 0', name='ck_agent_latency_nonnegative'),
    sa.CheckConstraint("status IN ('pending','running','completed','failed','cancelled')", name='ck_agent_executions_status'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_execution_id'], ['agent_executions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_executions_conversation_status_started', 'agent_executions', ['conversation_id', 'status', 'started_at'], unique=False)
    op.create_index('ix_agent_executions_trace', 'agent_executions', ['trace_id'], unique=False)
    op.create_table('message_citations',
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_id', sa.Uuid(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('relevance_score', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('quoted_text', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('rank >= 0', name='ck_message_citations_rank_nonnegative'),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'rank', name='uq_message_citations_message_rank')
    )
    op.create_table('approval_requests',
    sa.Column('agent_execution_id', sa.Uuid(), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=False),
    sa.Column('tool_name', sa.String(length=255), nullable=False),
    sa.Column('argument_preview', sa.JSON(), nullable=False),
    sa.Column('argument_digest', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_by', sa.Uuid(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_reason', sa.String(length=500), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("status IN ('pending','approved','rejected','expired','executing','executed','failed')", name='ck_approval_requests_status'),
    sa.CheckConstraint('version >= 1', name='ck_approval_requests_version'),
    sa.ForeignKeyConstraint(['agent_execution_id'], ['agent_executions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_approval_requests_status_expiry', 'approval_requests', ['status', 'expires_at'], unique=False)
    op.create_table('evaluation_results',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.String(length=255), nullable=False),
    sa.Column('execution_id', sa.Uuid(), nullable=True),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('score', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['agent_executions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id'], ['evaluation_runs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'case_id', 'metric_name', name='uq_evaluation_result_metric')
    )
    op.create_table('tool_executions',
    sa.Column('agent_execution_id', sa.Uuid(), nullable=False),
    sa.Column('approval_request_id', sa.Uuid(), nullable=True),
    sa.Column('tool_name', sa.String(length=255), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('safe_input', sa.JSON(), nullable=True),
    sa.Column('safe_output', sa.JSON(), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['agent_execution_id'], ['agent_executions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['approval_request_id'], ['approval_requests.id'], ondelete='RESTRICT'),
    sa.CheckConstraint("status IN ('pending','running','completed','failed')", name='ck_tool_executions_status'),
    sa.CheckConstraint('latency_ms IS NULL OR latency_ms >= 0', name='ck_tool_latency_nonnegative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('approval_request_id', name='uq_tool_executions_approval'),
    sa.UniqueConstraint('idempotency_key', name='uq_tool_executions_idempotency_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tool_executions')
    op.drop_table('evaluation_results')
    op.drop_index('ix_approval_requests_status_expiry', table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_table('message_citations')
    op.drop_index('ix_agent_executions_trace', table_name='agent_executions')
    op.drop_index('ix_agent_executions_conversation_status_started', table_name='agent_executions')
    op.drop_table('agent_executions')
    op.drop_table('user_roles')
    op.drop_table('role_permissions')
    op.drop_table('messages')
    op.drop_index('ix_document_chunks_document', table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_table('roles')
    op.drop_index('ix_refresh_sessions_user', table_name='refresh_sessions')
    op.drop_index('ix_refresh_sessions_family', table_name='refresh_sessions')
    op.drop_index('ix_refresh_sessions_expiry', table_name='refresh_sessions')
    op.drop_table('refresh_sessions')
    op.drop_index('ix_documents_owner_status_updated', table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_conversations_owner_updated', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('ix_audit_logs_resource', table_name='audit_logs')
    op.drop_index('ix_audit_logs_request', table_name='audit_logs')
    op.drop_index('ix_audit_logs_occurred', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('uq_users_active_email', table_name='users', postgresql_where=sa.text('is_deleted = false'))
    op.drop_table('users')
    op.drop_table('permissions')
    op.drop_table('evaluation_runs')
    # ### end Alembic commands ###
